project:
  type: website

website:
  title: "Murray Wood Works"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - shop.qmd
      - gallery.qmd
      - contact.qmd

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true



